### PR TITLE
Create ukrainian.yml

### PR DESCRIPTION
**Pull request by yaroslavrick**
Added ukrainian alphabet

### CODE REVIEW

**Comment by ehsainit** [comment]
would you release it ?

**Comment by yaroslavrick** [comment]
> would you release it ?

what do you mean?

**Comment by ehsainit** [comment]
as a gem, your last one didnt include the ukrainian language file

**Comment by dalibor** [comment]
I've released [0.3.0](https://rubygems.org/gems/cyrillizer/versions/0.3.0), give it a try.

**Comment by yaroslavrick** [comment]
Should I change some other files to make ukrainian language support in cyrillizer app? Or it will work if changed only cyrillizer/tree/master/lib)/alphabets/ukrainian.yml ?

**Comment by ehsainit** [comment]
@dalibor good thank you !

@yaroslavrick  according to the docs, it should be located under the alphabets folder

**Pull request merged**
